### ISSUE TITLE
Unable to Download Blocks on BitcoinZ Daemon

### ISSUE THREAD

**Issue by yodel-settles** [btcz/bitcoinz#109]
I'm encountering an issue where the BitcoinZ daemon fails to download any blocks.

Here are some additional details:
- Operating System: Ubuntu 24.04.1 LTS
- Daemon Version: 2.1.0 (BB-8) - Protocol 770009

I'm reaching out to the community for assistance in resolving this issue. Any suggestions or guidance would be greatly appreciated.

**Comment by ezzygarmyz** [comment]
> I'm encountering an issue where the BitcoinZ daemon fails to download any blocks.
> 
> Here are some additional details:
> 
> * Operating System: Ubuntu 24.04.1 LTS
> * Daemon Version: 2.1.0 (BB-8) - Protocol 770009
> 
> I'm reaching out to the community for assistance in resolving this issue. Any suggestions or guidance would be greatly appreciated.

add these lines in bitcoinz.conf file and restart the daemon...

addnode=74.208.91.217:8233
addnode=37.187.76.80:1989
addnode=explorer.btcz.app:1989
addnode=explorer.btcz.rocks:1989

**Comment by yodel-settles** [comment]
Thanks, that worked.
