### ISSUE TITLE
Wallet backup Ubuntu

### ISSUE THREAD

**Issue by Lumpenproleter** [btcz/bitcoinz#11]
So my node and wallet are working on Ubuntu 16.04.3. Bitcoinz installed from 1.0.11...
When trying to get backup of wallet or to export keys:
./src/zcash-cli z_exportwallet "filename=backup" "exportdir=/home/username/backup"
error code: -1
error message:
z_exportwallet "filename"
Now both parameters (filename and exportdir are also stated in bitcoinz.conf: exportdir=/home/username/backup
filename=backup )
For backup looks like this:
./src/zcash-cli dumpwallet "mybitcoinzhwallet"
error code: -4
error message:
Cannot export wallet until the zcashd -exportdir option has been set
Any ideas how to solve this?

**Comment by kiloutyg** [comment]
i'll advise you to get nanomsg it'll be easier with this: 
```
cd .bitcoinz
pico bitcoinz.conf
```

or modifiy /.bitcoinz/bitcoinz.conf with echo command:

`echo "exportdir=" >> ~/.bitcoinz/bitcoinz.conf`


or access .bitcoinz using ctrl+h like it's explain page 8 of bitcointalk thread

**Comment by ghost** [comment]
Run zcashd:
./zcashd -exportdir=.
Backup:
./zcash-cli z_exportwallet walletdata
Also copy wallet.dat (additional backup) or dump private keys for your addresses

Check starter guide https://github.com/bitcoinz-pod/bitcoinz/releases
