### ISSUE TITLE
Submissions Tracker to Pools, Exchanges, Sites

### ISSUE THREAD

**Issue by cryptorex** [btcz/bitcoinz#15]
# **Submissions Tracker to Pools, Exchanges, Sites**

**Please submit sites not listed here in comments section.**
**Please submit requests to the sites listed below.  This will be a community effort.**

**Exchanges to Submit To**

Kucoin: https://drive.google.com/open?id=1yhsPyrXQGHj6q4r2i-aNTv2sppKCFmAMW6aduA0TSXQ
Binance: https://drive.google.com/open?id=1EHpvQRWh_MKiYFw0PPQPAIMVDCGUgpPy4pk6EHBJljQ
Coss.io: https://drive.google.com/open?id=1gnod_vj0N0u1f93TGq24DePtPIN9TRublQO7Kv26L78
Poloniex: https://drive.google.com/open?id=1-oTYDSzbf5icg9tOvtnzRWuyifoLlGYTLIyczFhXvuY

https://abucoins.com/ *Submit Requests*
https://support.bittrex.com/hc/en-us/requests/new?ticket_form_id=114093958872 *Submitted* **Please submit more requests**
https://www.cryptopia.co.nz/Paytopia *cost 5million DOT*
https://evercoin.com/ *Similar to shapeshift, changelly.*
https://www.livecoin.net/
https://novaexchange.com/addcoin/ *Submitted* **Please submit more requests**
https://tidex.com/
https://yobit.net/en/addcoin/ *Submitted* **Please submit more requests**

**Pools**

https://www.nanopool.org email: *zec.nanopool@gmail.com* *In Process* **Please submit more requests**
https://www.f2pool.com email: *support@f2pool.com* *In Process* **Please submit more requests**
https://miningpoolhub.com/ email: *contact@miningpoolhub.com* *In Process* **Please submit more requests** 
https://coinotron.com email: *coinotron@gmail.com* *In Process* **Please submit more requests**
http://miningpools.cloud/ email: *cloudminingpools@gmail.com* *In Process* **Please submit more requests**
http://dwarfpool.com/contact/ email: *admin@dwarfpool.com* *In Process* **Please submit more requests**

**Sites**

**Sites**: https://www.crypto-coinz.net/crypto-calculator
**Sites**: https://whattomine.com/coins/207-btcz-equihash
**Sites**: https://www.cryptocompare.com/coins/btcz/overview
**Sites**: https://coinmarketcap.com/currencies/bitcoinz

**Wallets**

https://jaxx.io/ **Submit requests to show support**
https://trezor.io/ **Submit requests to show support**

**Completed Listings**

**Exchanges**: https://coinmarketcap.com/currencies/bitcoinz/#markets
C-cex, Stocks.Exchange, TradeSatoshi, BTC-Alpha, BarterDEX, Exrates

**Pool**: https://bitcoinz.getpool.network/ **DONATING 1.0% TO BTCZ PROJECT**
**Pool**: https://equipool.1ds.us **DONATING 2% TO BTCZ PROJECT**
**Pool**: http://pool.bitcoinzguiding.ovh/ **DONATING 0.2% to BTCZ PROJECT & BTCZ GIVEAWAYS**
**Pool**: https://zpool.wfmpools.com/ **DONATING 0.4% to BTCZ PROJECT**
**Pool**: https://lambomoon.club/ **DONATING 0.5% to BTCZ PROJECT**
**Pool**: https://worldminer.net **DONATING 0.3% to BTCZ PROJECT**
**Pool**: http://www.abakus.gemini.net.pl **DONATING 0.8% to BTCZ PROJECT**
**Pool**: https://pool.w00t.xyz/workers **DONATING 0.3% to BTCZ PROJECT**
**Pool**: http://45.77.41.80:8080/ **DONATING 0.7% to BTCZ PROJECT**
**Pool**: http://www.pcmining.xyz **DONATING 0.5% TO BTCZ PROJECT**
**Pool**: https://axepool.com/getting_started **DONATING 0.33% TO BTCZ PROJECT**
**Pool**: https://minez.zone
**Pool**: http://equi.mining4.co.uk
**Pool**: http://btz.pool.sexy
**Pool**: http://pool.miningspeed.com
**Pool**: http://miningpool.io
**Pool**: http://pool.coinminer.space:8090
**Pool**: http://www.zpool.ca/site/gomining?algo=equihash
**Pool**: https://btcz.suprnova.cc
**Pool**: https://pool.cryptobroker.io/btcz/
**Pool**: https://aikapool.com/btcz
**Pool**: https://luckpool.org/
**Pool**: https://zsolo.bid/ *Solo Mining Pool*
**Pool**: https://btczpool.com/
**Pool**: http://www.mineflowpool.pl/ [EN] [PL]
**Pool**: https://multipool.es/ [ES]
**Pool**: http://btcz.minertopia.org
**Pool**: http://owlminingclub.com/
**Pool**: http://eqpool.com/
**Pool**: http://z-traffic-pool.eu/

**Comment by bitcoinz-pod** [comment]
cryptopia
ccex
tradesatoshi

**Comment by jeremyd88** [comment]
BTCZ mining pool up and running at SuprNova! 
https://btcz.suprnova.cc

Cheers!
-NERDiT-

**Comment by barnyardlemon** [comment]
BTCZ mining pool up and running at btcZPool.com:

https://btcZPool.com

**Comment by cryptorex** [comment]
add btczpool to list on explorer and in this tracker.  thanks for joining the btcz movement!!!

**Comment by doublehao** [comment]
can you commit centos for bitcoinz release

**Comment by doublehao** [comment]
can you commit centos for bitcoinz release ?

**Comment by slydelv** [comment]
We've set up a new pool at http://btcz.wolfpool.io
Only fee is 1% which goes to the BitcoinZ donation fund.
Currently cracked around 52 blocks. Current hashrate around 235 K/Sols

**Comment by cryptorex** [comment]
@slydelv looks like that pool is down.

**Comment by egyptianbman** [comment]
@cryptorex are you against closing this issue? There's really no need for it anymore.

**Comment by cryptorex** [comment]
no
