### ISSUE TITLE
Debian package conflicts with Zcash

### ISSUE THREAD

**Issue by static-void-main** [btcz/bitcoinz#18]
Running sudo dpkg -i bitcoinz-1.1.1-a88eb5d-amd64.deb on a system with Zcash node already present gives the following error:

dpkg: error processing archive bitcoinz-1.1.1-a88eb5d-amd64.deb (--install):
 trying to overwrite '/usr/bin/zcash-fetch-params', which is also in package zcash 1.0.12

**Comment by renuzit** [comment]
We should probably rename the binaries. For now there is a docker version available btcz/bitcoinz

**Comment by ghost** [comment]
good point, but we are trying to stick close to zcash. For now it will not be possible to have zcash & bitcoinz at the same machine. We will need to think about docker image.
