### ISSUE TITLE
Pools are needed! Post pools in comments!

### ISSUE THREAD

**Issue by ghost** [btcz/bitcoinz#2]
Mining Pools
BTCZ Mining guide: http://bitcoinz.global/media/BitcoinZ_WALLET+MINING_GUIDE.pdf or https://t.co/NIHzRmPK0C
http://pool.miningspeed.com
https://pool.cryptobroker.io/btcz/
http://www.zpool.ca/site/mining
http://equi.mining4.co.uk
http://btz.pool.sexy
https://btcz.suprnova.cc
https://equipool.1ds.us
https://alphacentauri.science/
http://pool.coinminer.space:8090
http://www.pcmining.xyz/
https://aikapool.com/btcz
http://miningpool.io
http://luckpool.org
http://hashgate.eu/
https://bitcoinz.getpool.network/
https://zsolo.bid
https://equihashing.com
https://btczpool.com
http://www.mineflowpool.pl  [PL]
https://multipool.es [ES]
http://btcz.minertopia.org
http://owlminingclub.com

Mining software:
https://minez.zone/getting_started

Solo mining
https://github.com/z-classic/z-nomp
https://github.com/Austin-Williams/zcash-guides/wiki/Guide-to-Solo-Mining-Zcash

**Comment by danycoman** [comment]
For build pool , contact contact.mine.pool.ro@gmail.com (www.mine-pool.ro)

**Comment by sennevb** [comment]
pool.miningspeed.com now also supports bitcoinz!!

Will try to add block explorer later!

**Comment by sennevb** [comment]
Can you add me to the list, and also on bitcointalk??

**Comment by bitcoinz-pod** [comment]
@sennevb pool added!

**Comment by sanjay-shah** [comment]
Can you please add http://miningpool.io to the list?

**Comment by vtnplus** [comment]
z-nomp error payment "Insufficient funds (0) to process payments (39258.12568643); possibly waiting for txs."
pls help me fix it

**Comment by anthony19114** [comment]
a lot of these 100 BTCZ transactions because people are using z-nomp and its set to shield no more than 100 ZEC at a time


[1:40] 
they should raise the limit on z-nomp to 20000


[1:42] 
EDIT:
libs/paymentProcessor.js


[1:42] 
FIND AND CHANGE:
// unshield no more than 100 ZEC at a time
       if (amount > 20000.0)
           amount = 20000.0;

**Comment by vtnplus** [comment]
i have change but error when send form z-address to t-address ( commmand can run ok ) but nothing todo :(

**Comment by anthony19114** [comment]
Did you restart Z-NOMP? Give it some time to shield the operation.

**Comment by vtnplus** [comment]
yes i have restart. and restart bitconz. i have minning form btz start open block 2000. last time with mPOS work good. now i have open new server with z-nom but error :( payment
I have run z-nomp with zclassic. hush, zen all ok

**Comment by vtnplus** [comment]
here i problem Anthony 
sendmany "" {"t1eU8QrLMLASsPWufDmwZEjFrrrdXVzV2w8":1113.53944727,"t1fjjkKH9RiMvHyQSygEzjnLQnqmxuVEM4R":1426.0955063,"t1WEiThCYZT2KXuwmAkKs5sSKHiD6ujUKVd":1524.77700889,"t1gv7mdpwiJtZDqre1KoS96EhxUtba7cEiz":1105.05862271,"t1ZBWcZiTW3nfEJhdnwFK2gVHBLRpUd6tY2":1319.63507049,"t1SHyJhkc2TqC3awAinpqHocKrN2tXmfiv6":1256.41112389,"t1K4NvRtDsPa9siVp8oGCKbA7Q5uDKno93C":1090.47138718,"t1JKXhA4rk137te6NszDHpr1eB5gZiysAbb":1384.84578787,"t1YghGGDpQggRirntLTwBn5dedFDk8CN8uS":1013.02935266,"t1hAAZN8JPHgXkhXgAnRupRWwoFCv5HTZzi":2013.53585998}
2017-09-28 11:09:58 [Payments]  [bitconz] Error sending payments {"code":-6,"message":"Insufficient funds, coinbase funds can only be spent after they have been sent to a zaddr"}

What i need fix it

**Comment by anthony19114** [comment]
You have to have a zaddress defined in your pool config. and that shielding is on.
"requireShielding": true, 
that line goes into coins/bitcoinz.json
and you need a z address..
 "zAddress": "PUTZADDRESSHERE",

that line goes into your pool_configs/bitcoinz.json
. To get a Z address you would type ./bitcoinz/src/zcash-cli z_getnewaddress

**Comment by vtnplus** [comment]
all ready
my config 
"enabled": true,
    "coin": "bitcoinz.json",

    "address": "t1eUg3GNBZwNykpA5EGEQ4REUYknZMdCzTE",
    "_comment_address": "a transparent address to send coinbase rewards to and to transfer to zAddress.",

    "zAddress": "zcGWGFUHhWV1A4U6cKLWxho1fHJyngtxj3ovhxAERsERf4GCHNwB6hQJ8KDMw3nR9wNdLXPNF7vZw6rNsAww4Qb6UShD1aU",
    "_comment_zAddress": "a private address used to send coins to tAddress.",

    "tAddress": "t1frEP8ongcZxsDXiMus1YUoWCjH4pUkKs2",
    "_comment_tAddress": "transparent address used to send payments, make this a different address, otherwise payments will not send",

    "walletInterval": 2.5,
     "rewardRecipients": {
        "t1KqpjzyJgtxAZWgmSLio1aPCR67ZAQKuPd": 10
    },


    "tlsOptions": {
        "enabled": false,
        "serverKey":"",
        "serverCert":"",
        "ca":""
    },

    "paymentProcessing": {
        "minConf": 10,
        "enabled": true,
        "paymentMode": "pplnt",
        "_comment_paymentMode":"prop, pplnt",
        "paymentInterval": 180,
        "minimumPayment": 1000,
        "maxBlocksPerPayment": 1,
        "daemon": {
            .....
        }
    },

**Comment by hellcatz** [comment]
http://luckpool.org added bitcoinz

Coinbase hex for block explorer match up (mined by)
`Buffer('206c75636b706f6f6c2e6f726720687474703a2f2f6c75636b706f6f6c2e6f7267', 'hex')]) // luckpool.org http://luckpool.org`

https://bitcoinz.ph/block/000000011a2a9bdf6a0626f9bad92b85dcf553a3d937c136e0d92d543cd5b18a

**Comment by Leadspie** [comment]
New Bitcoinz pool, come mine with us at https://equihashing.com

**Comment by przemekh10** [comment]
I found another BitcoinZ pool: http://mineflowpool.pl/

**Comment by Leadspie** [comment]
Just use mine https://equihashing.com :) we need miners. 

Carmelo Milian
CEO at OneCloud
Http://OneCloudOps.com

**Comment by jorikfon** [comment]
http://owlminingclub.com added bitcoinz

**Comment by chilledgamer1985** [comment]
me and a friend have opened a small mining pool hosted in france with 0% fee
anyone is welcome to try with us 
[http://poolmining.info:8080](url)

**Comment by knottyuminus** [comment]
http://igloopool.org/

**Comment by Jlowzow** [comment]
Linux mining software?

**Comment by ziyaad30** [comment]
http://dash.cloudns.us

**Comment by zephyr2k7** [comment]
Can you please add http://minepool.ch to the list? We are the first Switzerland Pool

**Comment by thebestbaduser** [comment]
https://axepool.com/ (RU, Moscow)

**Comment by ghost** [comment]
Pls add: https://btcz.coinblockers.com

**Comment by radealpl** [comment]
https://worldminer.net/

**Comment by lucidletters** [comment]
http://geekhash.io
Lets keep the network decentralized.
- Payouts after 100 Confirmation on block.
- No fee* (fee may be added later only to maintain pool when we grow that large)
- No account needed. Just use your wallet address.
-BTCZ Is our main coin focus.
See you in the mines!
-Discord
https://discord.gg/h5PzHYs

**Comment by sneg55** [comment]
PPLNS: https://2miners.com/btcz-mining-pool 
SOLO: https://2miners.com/solo-btcz-mining-pool

**Comment by magnafic0** [comment]
please add us 
http://ezpool.ga/

**Comment by engbrown** [comment]
LET STOP WASTING TIME WHEN YOU CAN MAKE MONEY IN SIMPLE WAY WITHOUT DELAY CONFIGURE your wallet TO SERVER FREE!
Generate $3,030.58 to your BITCOIN WALLET.
minimum of 0.35 BTC a DAY!!
A week profit of 2.55BTC
No spams. No joint investment.
TAKE A TRIAL AND EARN.
Ask Me HOW.
You can email me now bitcoinminers50@gmail.com 
LETS GENERATE BITCOIN and be EARNERS!
