### ISSUE TITLE
JSON Payment Problems

### ISSUE THREAD

**Issue by savskii** [btcz/bitcoinz#26]
Hi, I am trying to install a pool and am getting these errors:

[Payments]  [bitcoinz] Error with RPC call listunspent undefined {"code":-1,"message":"JSON value is not a string as expected"}

Cant see where I am going wrong, I have tripple checked everything but cant find the problem

Thanks

![btcz](https://user-images.githubusercontent.com/4423195/33324062-b608e946-d44e-11e7-9161-5fb366959f8a.png)

**Comment by ghost** [comment]
please send bug to z-nomp project
