### ISSUE TITLE
android wallet  - failure to receive transaction

### ISSUE THREAD

**Issue by nilslarssonnla** [btcz/bitcoinz#29]
Hi,  I made a shipment to an android wallet and even that the transaction appears as completed, the wallet does not appear

https://btczexplorer.blockhub.info/tx/a8d99d5f07eb3d7f55770710a32518b874d3d3cee2e50374b2534ebccf287fab

**Comment by nilslarssonnla** [comment]
any dev?

**Comment by renuzit** [comment]
Did it finally appear in the wallet? You may need to rescan the addresses like so:
settings -> Select wallet -> more options -> addresses -> scan addresses for funds

Also, the official channel of support for the android wallet is here: https://github.com/bitcoinz-wallets/bitcoinz-copay-wallet

**Comment by ghost** [comment]
Please contact renuzit in slack.
