### ISSUE TITLE
Daemon freezes all the time and needs 10 minutes to start

### ISSUE THREAD

**Issue by przpl** [btcz/bitcoinz#46]
Why btcz daemon is so bad? I have other daemons on the same server and they work fine, but btcz daemon freezes for up to 2 minutes many times per day. It also needs 10 minutes (!) to load! What is wrong with it?

**Comment by egyptianbman** [comment]
I have a dozen nodes running on different computers and haven't experienced any issues with freezing or not loading. Have you tried reindexing? Also, make sure you're using the latest version.

If you continue to have issues, please provide more information on what hardware and operating system you're using.

**Comment by przpl** [comment]
Can this issue be related with not enough ram? I noticed that ram is almost out, and swap file is being used (3 GB of swap file).
I am using the newest daemon on Ubuntu 17.04.

**Comment by egyptianbman** [comment]
All zcash coins require at minimum 4GB memory when making z-transactions.

**Comment by przpl** [comment]
Yes, I know, but I have also BTC Private and Zclassic daemons on the same server performing shielding too, and they work flawless without any freezes. Also they don't need 10 minutes to start after restarting daemon.

**Comment by egyptianbman** [comment]
How big is your wallet.dat?

**Comment by przpl** [comment]
It seems to be big - 807 MB. Zclassic is 38 MB and BTC Private is 37 MB.

**Comment by egyptianbman** [comment]
Sounds like we've determined the problem. I would suggest migrating to a new wallet; thanks!
