### ISSUE TITLE
How to config btcz for pool z-nomp?

### ISSUE THREAD

**Issue by vanthoi** [btcz/bitcoinz#47]
My pool uses Z-NOMP for algo equihash.
I tried installing btcz on my pool. But it still only runs at the default algo equihash. Not algo equihash 145_5. So I want to run btcz on my pool. I have consulted through https://github.com/NickRHill/zh-nomp
I find the libraries here to be the default alog equihash unchanged from the Z-NOMP source code. Do not know if the developer made any suggestions for me? My experiment pool: https://super.mine-vn.com
Thank you!

**Comment by vanthoi** [comment]
Thank you for watching. I solved the problem.

**Comment by angona2** [comment]
@vanthoi How did you solve this issue?
