### ISSUE TITLE
Build fails while fetching libsnark

### ISSUE THREAD

**Issue by sanjay-shah** [btcz/bitcoinz#5]
Fetching libsnark...
https://z.cash/depends-sources/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz:
2017-09-12 05:26:46 ERROR 404: Not Found.
2017-09-12 05:26:46 URL:https://codeload.github.com/z-classic/libsnark/tar.gz/3854b20c25e8bc567aab2b558dec84d45f4a3e73 [144924/144924] -> "/home/pooladmin/bitcoinz/depends/work/download/libsnark-/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.temp" [1]
/home/pooladmin/bitcoinz/depends/work/download/libsnark-/libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.temp: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
funcs.mk:242: recipe for target '/home/pooladmin/bitcoinz/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash' failed
make: *** [/home/pooladmin/bitcoinz/depends/sources/download-stamps/.stamp_fetched-libsnark-libsnark-3854b20c25e8bc567aab2b558dec84d45f4a3e73.tar.gz.hash] Error 1

**Comment by tommyjs007** [comment]
The same problem on Ubuntu.

**Comment by joshyOcuk** [comment]
this is a larger issue to do with zcash
https://github.com/zcash/zcash/issues/2610

**Comment by ghost** [comment]
> this is a larger issue to do with zcash
zcash/zcash#2610

I don't think so, I have explained it [here](https://github.com/zcash/zcash/issues/2614).

**Comment by ghost** [comment]
Fixed in 1.0.1

**Comment by gdgrim** [comment]
I'm still getting the error while trying to build ZEN.
