### ISSUE TITLE
Win wallet

### ISSUE THREAD

**Issue by xoma11** [btcz/bitcoinz#6]
root@-Virtual-Machine:~/bitcoinz/zcutil# ./build-win.sh
+++ readlink -f ./build-win.sh
++ dirname /home/mikhail/bitcoinz/zcutil/build-win.sh
+ cd /home/mikhail/bitcoinz/zcutil/..
+ cd depends/
+ make HOST=x86_64-w64-mingw32 V=1 NO_QT=1
echo Extracting rust...
Extracting rust...
mkdir -p /home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a
cd /home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a; mkdir -p /home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a && echo "  /home/mikhail/bitcoinz/depends/sources/" > /home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a/..hash &&  sha256sum -c /home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a/..hash && tar --strip-components=1 -xf /home/mikhail/bitcoinz/depends/sources/
sha256sum: /home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a/..hash: no properly formatted SHA256 checksum lines found
funcs.mk:242: recipe for target '/home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a/.stamp_extracted' failed
make: *** [/home/mikhail/bitcoinz/depends/work/build/x86_64-w64-mingw32/rust/1.16.0-3285257568a/.stamp_extracted] Error 1
+ ./autogen.sh
./build-win.sh: line 44: ./autogen.sh: No such file or directory

I check files sha256 is ok.
I dont know thats a problem =(

**Comment by xoma11** [comment]
Fetching rust...
2017-09-13 17:25:31 URL:https://z.cash/depends-sources/ [7520] -> "/home/mikhail                                                                                                                                                             /bitcoinz/depends/work/download/rust-1.16.0/.temp" [1]
sha256sum: /home/mikhail/bitcoinz/depends/work/download/rust-1.16.0/..hash: no p                                                                                                                                                             roperly formatted SHA256 checksum lines found
funcs.mk:242: recipe for target '/home/mikhail/bitcoinz/depends/sources/download                                                                                                                                                             -stamps/.stamp_fetched-rust-.hash' failed
make: *** [/home/mikhail/bitcoinz/depends/sources/download-stamps/.stamp_fetched                                                                                                                                                             -rust-.hash] Error 1
+ ./autogen.sh
./build-win.sh: line 44: ./autogen.sh: No such file or directory

**Comment by icyberdeveloper** [comment]
same issue

**Comment by ghost** [comment]
Windows repo compiles correctly: https://github.com/bitcoinz-pod/bitcoinz-win
