### ISSUE TITLE
Add founderaddress to gbt

### ISSUE THREAD

**Issue by crackfoo** [btcz/bitcoinz#66]
Hi, 

The founder reward amount is listed in getblocktemplate however the current address is not. Can you please add this into the gbt results?

Thanks

**Comment by MarcelusCH** [comment]
Hi, yes this can be added in the `getblocktemplate` result, implemented as following  into `mining.cpp`: 

- Including the key_io library : `#include "key_io.h"`
- And getting back the address from the public script (just after the foundersreward pair): 
```
                const CScript & scriptPublicKey = tx.vout[1].scriptPubKey  ;
                std::vector<CTxDestination> addresses;
                txnouttype whichType;
                int nRequired;

                ExtractDestinations(scriptPublicKey, whichType, addresses, nRequired);
                //entry.push_back(Pair("script", GetTxnOutputType(whichType)));
                //entry.push_back(Pair("hex", HexStr(scriptPublicKey.begin(), scriptPublicKey.end())));
                UniValue a(UniValue::VARR);
                for (const CTxDestination& addr : addresses) {a.push_back(EncodeDestination(addr));}
                entry.push_back(Pair("foundersraddress", a));
```
This can be added in the 2.1.0 update :
![Screenshot from 2022-06-05 12-48-53](https://user-images.githubusercontent.com/37587839/172047353-edba6791-ff0d-4667-8582-fd7648371d78.png)

And here the result :
![Screenshot from 2022-06-05 12-58-21](https://user-images.githubusercontent.com/37587839/172047352-22171b2d-240b-4f47-abeb-4bd089312752.png)

**Comment by crackfoo** [comment]
thanks so much! makes it much easier to pickup the founder address changes.

**Comment by MarcelusCH** [comment]
Added into 2.0.8 release !

**Comment by crackfoo** [comment]
Did this not get put into the latest version? Is founder payout no longer required?

**Comment by crackfoo** [comment]
never mind. missed the note about no founder anymore
